# Section 3: NumPy

# NumPy 

- N dimensional arrays (one dimensional vector , two dimensional matrix ...)
- Random number capabilities 
- Built in statistical distributions

## Creating NumPy Array

In [2]:
import numpy as np

In [3]:
a = [1,2,3]

In [4]:
type(a)

list

In [7]:
b = np.array(a)
b

array([1, 2, 3])

In [6]:
type(b)

numpy.ndarray

In [7]:
b

array([1, 2, 3])

In [13]:
np.array(range(0,10))   # Remember we used the range() method earlier

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(0,10)  # arange() is a function in numpy to create an array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
np.linspace(0,5,6)  #equally spaced from 0 to 5 included 6 numbers(float)

array([0., 1., 2., 3., 4., 5.])

In [22]:
np.linspace(0, 3, 31)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. ])

In [11]:
c = [[1, 2, 3], [10, 20, 30]]  # Let's make a two dimensional array

In [12]:
np.array(c)

array([[ 1,  2,  3],
       [10, 20, 30]])

In [15]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [16]:
np.zeros((3,4))    # For multidimesional argument, use tuple

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
first_thirty = np.linspace(0, 29, 30)
print(first_thirty)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29.]


In [10]:
first_thirty.shape

(30,)

In [11]:
first_thirty.reshape(3,10)

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14., 15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24., 25., 26., 27., 28., 29.]])

## Selecting from Numpy Array

In [15]:
import numpy as np

In [47]:
first_ten = np.arange(0,10)
print(first_ten)

[0 1 2 3 4 5 6 7 8 9]


In [48]:
first_ten[3]

3

In [49]:
first_ten[3:5]   #starting from index 3 (including) to index 5 (excluding)

array([3, 4])

In [50]:
first_ten[:2]    # starting from the begining, to index 2 (excluding)

array([0, 1])

In [51]:
first_ten[6:]     # starting from 6 (including) to end

array([6, 7, 8, 9])

In [17]:
first_thirty = np.linspace(0, 29, 30)
three_by_ten = first_thirty.reshape(3,10)
print(three_by_ten)
print(three_by_ten.shape)

[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]
 [20. 21. 22. 23. 24. 25. 26. 27. 28. 29.]]
(3, 10)


In [59]:
three_by_ten[1]

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19.])

In [64]:
three_by_ten[1,5]

15.0

In [18]:
three_by_ten[0:2, 1:3]

array([[ 1.,  2.],
       [11., 12.]])

In [82]:
tens = np.arange(0,101,10)  # From 0(included) t0 101(excluded) in steps of 10
print(tens)

[  0  10  20  30  40  50  60  70  80  90 100]


In [83]:
tens >= 60

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [85]:
tens[6:]

array([ 60,  70,  80,  90, 100])

In [87]:
tens[tens >= 60]

array([ 60,  70,  80,  90, 100])

## Operations

In [19]:
import numpy as np

In [22]:
first_ten = np.arange(0,10)
print(first_ten)

[0 1 2 3 4 5 6 7 8 9]


In [23]:
first_ten + 10

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [92]:
first_ten - 10

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1])

In [24]:
first_ten + first_ten

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [94]:
first_ten * first_ten

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [100]:
# [1,2,3,4] + 10   # The same thing (broadcasting) does not work on a list

## Changing Array Elements

In [25]:
first_ten = np.arange(0,10)
print(first_ten)

[0 1 2 3 4 5 6 7 8 9]


In [26]:
first_ten[0] = 10

In [27]:
first_ten

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [28]:
first_ten[:] = 10   # lets set all elements in this array to 10 ... Number 10 has been broadcasted to all elements
first_ten

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

In [73]:
first_ten = np.arange(0,10)
print(first_ten)
first_five = first_ten[0:5]
print(first_five)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]


In [75]:
first_five[:] = 0
first_five

array([0, 0, 0, 0, 0])

In [76]:
print(first_ten)   # first_five was pointing to the values in first_ten. Any change in it affected the parent array as well.

[0 0 0 0 0 5 6 7 8 9]
